### ISSUE TITLE
Found 0 contatcs

### ISSUE THREAD

**Issue by PtkFerraro** [Temptin/SkypeExport#19]
I have a main.db that works with some chats and when I run the Skypexport, it says "Found 0 contacts in the database...Export finished..."

**Comment by sthoduka** [comment]
Hey @PtkFerraro,
what do you mean by "works with some chats"? Does it mean that you do get some results when you run SkypeExport?

Could you try opening the file with http://sqlitebrowser.org/ to see if you have anything in the Contacts table?

**Comment by PtkFerraro** [comment]
Hi @sthoduka ,

When I open in SqlBrowser, it shows all the tables but all of them are empty.

I meant that in one of my notebooks (one account) works (it exports) and in another notebook (another account) it doesn´t export.

The file has 30mb. Why would come empty if I open Skype and have all chats on it?

**Comment by sthoduka** [comment]
Yea it's strange that the tables are empty if your db is 30 mb. At least some of the tables must have data. Could you check all tables? 
Also, which operating system and version of Skype are you using?

**Comment by PtkFerraro** [comment]
@sthoduka , just ran again and it´s working fine. Maybe was some problem in tue copy. 

cheers.
