### ISSUE TITLE
Feature Request: Export Group Conversations

### ISSUE THREAD

**Issue by nicolinux** [Temptin/SkypeExport#8]
It would be extremely useful to support the export of group chats/conversations. I have tried to export everything (didn't specify -c) and I've got .html files for contact names, not group chats.

Thanks!

**Comment by Temptin** [comment]
Hi Nico!

Your exported contacts contain all group chats they've ever been part of. If you scroll through their history html files, you will see links like "You started a group chat with [person]", with a clickable link that scrolls down the page to that exact group chat. Or, if you prefer, scroll all the way down immediately and you'll see them.

I preferred to do it that way (instead of separate files per conference), because it makes sense to have all of that person's group chats in a single file along with the other conversations with that person.

I hope that answers your question? :)

Sincerely,
Johnny

**Comment by nicolinux** [comment]
Hey Johnny,

Thanks for the quick answer. You are right, it is there. But there are cases where this option would be very useful. If I want to share just the group chat with somebody else, I'd need to go through the entire (huge) exported file and cut out only the group chat part.

Thanks,
Stefan

**Comment by Temptin** [comment]
Ahh... I wouldn't use such a feature and don't have time to add it, super busy with other work right now. Do you know C/C++? If so I suggest you fork it, do the changes, test them and submit a pull request. :)

Here's what would need changing:

main.cpp: New flag "-m/--mode" (string, values "full", "1on1" and "group"), converted into an integer (0 = full, 1 = 1on1, 2 = group)
https://github.com/Temptin/SkypeExport/blob/master/src/SkypeExport/main.cpp#L13

main.cpp: Pass the mode integer to the exportUserHistory function as a new, final parameter
https://github.com/Temptin/SkypeExport/blob/master/src/SkypeExport/main.cpp#L123

skypeparser_parsing.cpp: Accept the new parameter (also in the .h header file)
https://github.com/Temptin/SkypeExport/blob/master/src/SkypeExport/model/skypeparser_parsing.cpp#L7

skypeparser_parsing.cpp: Only output regular chat history if mode integer == 0 or 1, and pass the mode into the getHistoryAsXHTML() function
https://github.com/Temptin/SkypeExport/blob/master/src/SkypeExport/model/skypeparser_parsing.cpp#L26

skypeparser_parsing.cpp: Only output regular group history if mode integer == 0 or 2, and pass the mode into the getHistoryAsXHTML() function
https://github.com/Temptin/SkypeExport/blob/master/src/SkypeExport/model/skypeparser_parsing.cpp#L29

skypeparser_parsing.cpp: If mode integer != 0 (both 1on1+group), then do not output links to the group chats inside the main history
https://github.com/Temptin/SkypeExport/blob/master/src/SkypeExport/model/skypeparser_parsing.cpp#L920
https://github.com/Temptin/SkypeExport/blob/master/src/SkypeExport/model/skypeparser_parsing.cpp#L922

And a few tiny cleanups here and there, stuff like:

skypeparser_parsing.cpp: Put a tag such as " (Group Chats Only)"/" (Group Conversations Only)" and " (One-on-One)" in the page title if mode integer == 1 or 2, to make it obvious that the mode was used
https://github.com/Temptin/SkypeExport/blob/master/src/SkypeExport/model/skypeparser_parsing.cpp#L18

main.cpp: Put "_groupchats.skypelog.htm" or "_1on1.skypelog.htm" if mode 1 or 2 is used, to make it non-collide with regular full history files (and makes it easy to see what mode was used without having to open the file)
https://github.com/Temptin/SkypeExport/blob/master/src/SkypeExport/main.cpp#L118

If you'd prefer that the group chats be exported as individual .html files named after the group chats then that would be a _lot_ of work but feel free to try... ;)

If you do any work on this then I'll review it and merge it when it's time for the next minor maintenance release (there was a tiny issue discovered with Microsoft's rare, internal "live:[name]" Skype names which have a silly colon in the name, which makes those history files unwritable on Windows).

**Comment by Temptin** [comment]
^ Updated above with a more flexible solution.

**Comment by nicolinux** [comment]
Hi,

Thank you for the info but sadly I don't have the time and motivation to work on this. I have already accomplished my task. I may return to it later but I can't promise.

**Comment by Temptin** [comment]
@nicolinux That makes two of us. I am too busy as well, hehe. And the feature would be more useful if it exports the group chats as individual files, so I'm not exactly motivated to add this crippled version of the idea (which puts all groups for that person in a single file)... But making it export every group chat as individual files would be way too much work. Well, if you ever feel like it or have some idea, you can comment on this ticket again. If not, we'll consider it done. Take care. :)
