### ISSUE TITLE
images snapshots

### ISSUE THREAD

**Issue by BDYXS** [Temptin/SkypeExport#9]
Hi, excellent work ))
Is there a way to show snapshots and/or real images linked on the resulting .htm file?

John is sending you a file:
 _image.jpg (Cloud File Transfer)

Thanks!!

**Comment by Temptin** [comment]
Hi smartfore, I would also have loved to add that feature, but Skype's cloud image service requires the sender or recipient to log in before the thumbnails/full images can be downloaded. :/
